format = """
$username\
$directory\
$git_branch\
$git_state\
$character """

add_newline = false

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
vimcmd_symbol = "[](green)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[directory]
read_only = " 󰌾"
read_only_style = "white"

[git_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Android = " "
Arch = " "
Debian = " "
Fedora = " "
Linux = " "
Macos = " "
NixOS = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[python]
symbol = " "
version_format = "${raw}"

[rust]
symbol = " "